from domain.PDFVectorDatabase import PDFVectorDatabase
from domain.LLMProcessor import LLMProcessor

class Main:
    """
    Main class to handle user interactions and process questions 
    using the LLMProcessor and PDF vector database.

    Attributes:
        model (LLMProcessor): An instance of the LLMProcessor for processing questions.
        vector_database (PDFVectorDatabase): An instance of the PDFVectorDatabase for searching data.
    """

    def __init__(self):
        """
        Initializes the Main class with instances of LLMProcessor and PDFVectorDatabase.
        """
        self.model = LLMProcessor()
        self.vector_database = PDFVectorDatabase()

    def handle_user_question(self, question: str) -> str:
        """
        Handles a user's question by searching for relevant data in the vector database
        and processing the question using the LLMProcessor.

        Parameters:
            question (str): The question posed by the user.

        Returns:
            str: The response generated by the LLMProcessor based on the user's question
                 and the queried data from the vector database.
        """
        response = self.model.execute_question(question)
        return response
